// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDomain(arg1:string,arg2:string):Promise<main.Domain>;

export function ConnectSsh(arg1:string,arg2:number,arg3:string,arg4:string):Promise<main.SshConnectResponse>;

export function DeleteData(arg1:string):Promise<any>;

export function DisconnectTerminal():Promise<void>;

export function FetchData(arg1:string):Promise<any>;

export function GetCurrentUser():Promise<main.User>;

export function GetDeployments():Promise<Array<main.Deployment>>;

export function GetDomains():Promise<Array<main.Domain>>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetProjects():Promise<Array<main.Project>>;

export function IsTerminalConnected():Promise<boolean>;

export function NewConsole():Promise<main.Console>;

export function NewWsMessage():Promise<main.WsMessage>;

export function PostData(arg1:string,arg2:any):Promise<any>;

export function ResizeTerminal(arg1:number,arg2:number):Promise<void>;

export function SendTerminalInput(arg1:string):Promise<void>;

export function SignIn(arg1:string):Promise<main.AuthResponse>;

export function SignOut():Promise<boolean>;

export function StartTerminalWebSocket(arg1:string,arg2:string):Promise<void>;

export function StoreSession(arg1:string):Promise<void>;

export function UpdateData(arg1:string,arg2:any):Promise<any>;
