// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDomain(arg1, arg2) {
  return window['go']['main']['App']['AddDomain'](arg1, arg2);
}

export function ConnectSsh(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectSsh'](arg1, arg2, arg3, arg4);
}

export function DisconnectTerminal() {
  return window['go']['main']['App']['DisconnectTerminal']();
}

export function GetDeployments() {
  return window['go']['main']['App']['GetDeployments']();
}

export function GetDomains() {
  return window['go']['main']['App']['GetDomains']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function IsTerminalConnected() {
  return window['go']['main']['App']['IsTerminalConnected']();
}

export function NewConsole() {
  return window['go']['main']['App']['NewConsole']();
}

export function NewWsMessage() {
  return window['go']['main']['App']['NewWsMessage']();
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2);
}

export function SendTerminalInput(arg1) {
  return window['go']['main']['App']['SendTerminalInput'](arg1);
}

export function SignIn(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SignIn'](arg1, arg2, arg3, arg4, arg5);
}

export function StartTerminalWebSocket(arg1, arg2) {
  return window['go']['main']['App']['StartTerminalWebSocket'](arg1, arg2);
}

export function VerifyMagicCode(arg1, arg2, arg3) {
  return window['go']['main']['App']['VerifyMagicCode'](arg1, arg2, arg3);
}
