// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDomain(arg1, arg2) {
  return window['go']['main']['App']['AddDomain'](arg1, arg2);
}

export function ConnectSsh(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectSsh'](arg1, arg2, arg3, arg4);
}

export function CreateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3);
}

export function DeleteProject(arg1, arg2) {
  return window['go']['main']['App']['DeleteProject'](arg1, arg2);
}

export function DisconnectTerminal() {
  return window['go']['main']['App']['DisconnectTerminal']();
}

export function GetDeployments(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetDeployments'](arg1, arg2, arg3, arg4);
}

export function GetDomains() {
  return window['go']['main']['App']['GetDomains']();
}

export function GetLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2, arg3, arg4);
}

export function GetProjects(arg1, arg2) {
  return window['go']['main']['App']['GetProjects'](arg1, arg2);
}

export function IsTerminalConnected() {
  return window['go']['main']['App']['IsTerminalConnected']();
}

export function NewConsole() {
  return window['go']['main']['App']['NewConsole']();
}

export function NewWsMessage() {
  return window['go']['main']['App']['NewWsMessage']();
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2);
}

export function SendTerminalInput(arg1) {
  return window['go']['main']['App']['SendTerminalInput'](arg1);
}

export function SignIn(arg1, arg2, arg3) {
  return window['go']['main']['App']['SignIn'](arg1, arg2, arg3);
}

export function StartTerminalWebSocket(arg1, arg2) {
  return window['go']['main']['App']['StartTerminalWebSocket'](arg1, arg2);
}

export function UpdateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3);
}

export function VerifyMagicCode(arg1, arg2, arg3) {
  return window['go']['main']['App']['VerifyMagicCode'](arg1, arg2, arg3);
}
