// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function SignIn(arg1) {
  return window['go']['main']['App']['SignIn'](arg1);
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}

export function StoreSession(arg1) {
  return window['go']['main']['App']['StoreSession'](arg1);
}
