import type { main } from "../../wailsjs/go/models";

// Use the autogenerated classes as types
export type User = main.User;
export type Project = main.Project;
export type LogEntry = main.LogEntry;
export type Deployment = main.Deployment;
export type Domain = main.Domain;

// Only create additional interfaces for frontend-specific state
export interface AppState {
  selectedSection: string;
  selectedProjectId: string | null;
  selectedDeploymentId: string | null;
}

export interface Account {
  name: string;
  avatar: string;
}

export type ThemeType = 'light' | 'dark' | 'system';
export type ViewMode = 'grid' | 'list';