import type { types } from "../../wailsjs/go/models";

// Use the autogenerated classes as types
export type User = types.User;
export type Project = types.Project;
export type LogEntry = types.LogEntry;
export type Deployment = types.Deployment;
export type Domain = types.Domain;
export type Console = types.Console;
export type WsMessage = types.WsMessage;

// Only create additional interfaces for frontend-specific state
export interface AppState {
  selectedSection: string;
  selectedProjectId: string | null;
  selectedDeploymentId: string | null;
}

export interface Account {
  name: string;
  avatar: string;
}

export type ThemeType = 'light' | 'dark' | 'system';
export type ViewMode = 'grid' | 'list';