import type { models } from "../../wailsjs/go/models";

// Use the autogenerated classes as types
export type User = models.User;
export type Project = models.Project;
export type LogEntry = models.LogEntry;
export type Deployment = models.Deployment;
export type Domain = models.Domain;
export type Console = models.Console;
export type WsMessage = models.WsMessage;

// Only create additional interfaces for frontend-specific state
export interface AppState {
  selectedSection: string;
  selectedProjectId: string | null;
  selectedDeploymentId: string | null;
}

export interface Account {
  name: string;
  avatar: string;
}

export type ThemeType = 'light' | 'dark' | 'system';
export type ViewMode = 'grid' | 'list';